### ISSUE TITLE
Gem should not rely on just Middelman

### ISSUE THREAD

**Issue by iwarner** [yterajima/middleman-robots#11]
Hiya

some people may utilise just the bare bones install of middleman, i.e.

~~~
# Middleman core
# @see https://github.com/middleman
gem 'middleman-core', git: 'https://github.com/middleman/middleman.git', branch: 'master'
gem 'middleman-cli', git: 'https://github.com/middleman/middleman.git', branch: 'master'
~~~

This way I dont get Coffee or Haml or other unwanted gems

and therefore

    spec.add_runtime_dependency 'middleman', '>= 4.0'

this faile

**Comment by yuya-matsushima** [comment]
I am sorry that the correspondence was delayed.
Now, middleman-robots v0.3.4 is released. That does not rely on middleman.
