### ISSUE TITLE
Building fail

### ISSUE THREAD

**Issue by manoufeb** [yterajima/middleman-robots#8]
Hi,

When build  I have this error : 
`No such file or directory @ rb_sysopen - /var/folders/rh/ng8mv_5x24dbkvp87l189dnw0000gn/T/middleman-robots20170509-38873-1dv9lw4
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/util/binary.rb:70:in read'
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/util/binary.rb:70:in file_contents_include_binary_bytes?'`

Here is my Gemfile:
`gem 'middleman', '~> 4.0'
gem 'middleman-livereload'
gem 'middleman-sprockets', github: 'middleman/middleman-sprockets'
gem 'builder'
gem 'middleman-robots', '~> 1.3.1'`

Ps: it's working fine one 1.3.0 ;) 

Don't hesitate if ou have any question! 
Thanks

**Comment by yuya-matsushima** [comment]
Thank you for the report. I think it is probably a problem with tempfile access permissions. 
v1.3.2 is released. Please try new version.
